import { Link } from "wouter";
import { ArrowLeft, FileText, ShieldCheck } from "lucide-react";
import VelvetNav from "@/components/VelvetNav";

const policySections = [
  ["Privacy policy", "Titolare del trattamento: [INSERIRE RAGIONE SOCIALE E INDIRIZZO UFFICIALE]. Contatto privacy: [INSERIRE EMAIL PRIVACY]. Il negozio tratta i dati necessari per account, ordini, assistenza, pagamenti e adempimenti di legge. Non inserire dati sensibili nel campo note ordine. Completa questa sezione con basi giuridiche, tempi di conservazione, destinatari, trasferimenti e diritti dell’interessato prima della pubblicazione."],
  ["Termini e condizioni", "Il servizio è destinato a persone maggiorenni. Il cliente deve fornire dati veritieri e utilizzare il sito nel rispetto della legge. Prezzi, disponibilità, imposte e costi di consegna sono mostrati prima della conferma dell’ordine. Titolare, legge applicabile, assistenza e procedura di reclamo devono essere completati con i dati ufficiali dell’attività."],
  ["Spedizioni", "Spediamo da [INSERIRE PAESE/MAGAZZINO]. Tempi stimati: [INSERIRE TEMPI REALI]. Paesi serviti: [INSERIRE PAESI]. Costi, tracciamento, eventuali dazi e condizioni di consegna devono corrispondere alle impostazioni effettive di Shopify e del corriere. Per prodotti adult wellness e intimo, usa imballaggio discreto solo se realmente disponibile."],
  ["Resi e rimborsi", "Richieste a [INSERIRE EMAIL ASSISTENZA] entro [INSERIRE TERMINE]. Per motivi igienici, alcuni prodotti intimi o adult wellness sigillati possono essere esclusi dal recesso quando la confezione è stata aperta, nei limiti della legge applicabile. Specifica procedura, indirizzo di restituzione, prodotti esclusi, tempi di rimborso e responsabilità delle spese prima di pubblicare."],
  ["Age gate e sicurezza", "Il catalogo adulto è riservato a persone di almeno 18 anni. Il sito non vende contenuti sessuali espliciti e non tollera minori, coercizione, molestie o sfruttamento. La conferma dell’età non sostituisce eventuali controlli richiesti dalla legge o dal provider di pagamento."],
];

export default function Policies() {
  return <div className="velvet-shell min-h-screen"><VelvetNav compact /><main className="container max-w-4xl py-12 md:py-20"><Link href="/" className="inline-flex items-center gap-2 text-xs font-bold text-[#d7b46a]"><ArrowLeft size={15} /> Torna al club</Link><div className="mt-10 flex items-start gap-4"><div className="grid h-12 w-12 shrink-0 place-items-center rounded-full bg-[#d7b46a] text-[#100b0c]"><FileText size={22} /></div><div><p className="section-kicker">Store policy / 18+</p><h1 className="display-font mt-3 text-5xl text-white md:text-7xl">Informazioni chiare.</h1><p className="mt-5 max-w-2xl text-base leading-8 text-[#b9aaba]">Questa pagina raccoglie la struttura delle policy del negozio. I campi tra parentesi quadre sono obbligatori: sostituiscili con i dati ufficiali prima di pubblicare o vendere.</p></div></div><div className="mt-12 space-y-4">{policySections.map(([title, body]) => <section key={title} className="rounded-3xl border border-white/10 bg-white/[.035] p-6 md:p-8"><h2 className="display-font text-3xl text-white">{title}</h2><p className="mt-4 text-sm leading-7 text-[#c4b6c4]">{body}</p></section>)}</div><div className="mt-8 flex gap-3 rounded-3xl border border-[#d7b46a]/25 bg-[#d7b46a]/10 p-6 text-sm leading-6 text-[#f0d18a]"><ShieldCheck className="mt-1 shrink-0" size={18} /> <p>Questa struttura non è consulenza legale e non sostituisce i testi ufficiali richiesti per la tua attività, il tuo paese o il tuo provider di pagamento.</p></div></main></div>;
}
