import { useMemo, useState } from "react";
import { ArrowUpRight, ExternalLink, Heart, Info, ShieldCheck, Sparkles, Tag } from "lucide-react";
import VelvetNav from "@/components/VelvetNav";
import { toast } from "sonner";

type Category = "Tutto" | "Wellness" | "Intimo" | "Accessori";
type Product = { id: string; category: Exclude<Category, "Tutto">; name: string; description: string; price: string; tone: string; partner: string; href: string };

const products: Product[] = [
  { id: "01", category: "Wellness", name: "Rituale al velluto", description: "Selezione wellness per un momento lento e consapevole.", price: "€ 24,90", tone: "from-[#4b2230] to-[#1b101b]", partner: "Partner in selezione", href: "#partner" },
  { id: "02", category: "Intimo", name: "Set notte privata", description: "Intimo editoriale dalle linee essenziali e morbide.", price: "€ 39,90", tone: "from-[#2e243a] to-[#110b17]", partner: "Partner in selezione", href: "#partner" },
  { id: "03", category: "Accessori", name: "Kit aftercare", description: "Accessori per cura, igiene e conservazione responsabile.", price: "€ 18,50", tone: "from-[#463225] to-[#160e12]", partner: "Partner in selezione", href: "#partner" },
  { id: "04", category: "Wellness", name: "Calma privata", description: "Un prodotto wellness da scegliere con istruzioni chiare e materiali dichiarati.", price: "€ 32,00", tone: "from-[#352443] to-[#120b19]", partner: "Partner in selezione", href: "#partner" },
  { id: "05", category: "Intimo", name: "Linea Red Velvet", description: "Dettaglio sartoriale pensato per un guardaroba intimo personale.", price: "€ 44,00", tone: "from-[#572833] to-[#180c15]", partner: "Partner in selezione", href: "#partner" },
  { id: "06", category: "Accessori", name: "Custodia discreta", description: "Soluzione pratica per ordine, privacy e conservazione.", price: "€ 16,90", tone: "from-[#2d3742] to-[#10151c]", partner: "Partner in selezione", href: "#partner" },
];

export default function Store() {
  const [category, setCategory] = useState<Category>("Tutto");
  const [favorites, setFavorites] = useState<string[]>([]);
  const visible = useMemo(() => category === "Tutto" ? products : products.filter(product => product.category === category), [category]);
  const toggleFavorite = (id: string) => setFavorites(current => current.includes(id) ? current.filter(item => item !== id) : [...current, id]);
  const handlePartnerClick = (product: Product) => toast("Catalogo affiliate in configurazione", { description: `${product.name}: il link sarà attivo dopo la verifica del partner.` });
  return <div className="velvet-shell min-h-screen"><VelvetNav /><main className="container py-12 md:py-16">
    <section className="grid gap-8 lg:grid-cols-[1fr_360px] lg:items-end"><div><p className="section-kicker">Red Velvet / Store</p><h1 className="display-font mt-3 text-5xl leading-[.98] text-white md:text-7xl">Oggetti per<br /><span className="text-[#d7b46a]">rituali privati.</span></h1><p className="mt-6 max-w-2xl text-lg leading-8 text-[#c8bdc8]">Una selezione editoriale di wellness, intimo e accessori. Il Red Velvet Club presenta i prodotti; il partner verificato gestisce acquisto, pagamento, spedizione e resi.</p></div><div className="rounded-3xl border border-[#d7b46a]/25 bg-[#190e22] p-6"><div className="flex items-start gap-3"><ShieldCheck className="mt-1 text-[#d7b46a]" size={21} /><div><p className="section-kicker">Modello affiliate</p><h2 className="mt-2 text-xl font-extrabold text-white">Nessun magazzino. Nessuna custodia.</h2><p className="mt-3 text-sm leading-6 text-[#b8a8b4]">Il catalogo è predisposto per link affiliati reali. Nessun prodotto o partner viene presentato come disponibile finché non è stato verificato.</p></div></div></div></section>
    <section className="mt-10 flex flex-wrap items-center justify-between gap-4"><div className="flex flex-wrap gap-2">{(["Tutto", "Wellness", "Intimo", "Accessori"] as Category[]).map(item => <button key={item} onClick={() => setCategory(item)} className={`rounded-full border px-4 py-2 text-xs font-extrabold ${category === item ? "border-[#d7b46a] bg-[#d7b46a] text-[#09070d]" : "border-white/15 text-[#cbbdca] hover:bg-white/10"}`}>{item}</button>)}</div><p className="text-xs text-[#958493]">{visible.length} selezioni curate · prezzi indicativi</p></section>
    <section className="mt-6 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{visible.map(product => <article key={product.id} className="group overflow-hidden rounded-3xl border border-white/10 bg-[#120b19]"><div className={`relative flex h-52 items-end bg-gradient-to-br ${product.tone} p-5`}><span className="absolute left-5 top-5 rounded-full border border-[#d7b46a]/40 bg-black/20 px-3 py-1 text-[10px] font-extrabold uppercase tracking-[.14em] text-[#f1d58f]">{product.category}</span><button aria-label={favorites.includes(product.id) ? "Rimuovi dai preferiti" : "Aggiungi ai preferiti"} onClick={() => toggleFavorite(product.id)} className="absolute right-5 top-5 grid h-9 w-9 place-items-center rounded-full border border-white/15 bg-black/20 text-white"> <Heart size={15} fill={favorites.includes(product.id) ? "currentColor" : "none"} /></button><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#e0c684]">Red Velvet edit</p><p className="mt-2 text-2xl font-black text-white">{product.name}</p></div></div><div className="p-5"><p className="text-sm leading-6 text-[#b8a8b4]">{product.description}</p><div className="mt-5 flex items-center justify-between"><strong className="text-lg text-[#f1d58f]">{product.price}</strong><span className="text-[10px] uppercase tracking-[.12em] text-[#958493]">{product.partner}</span></div><button onClick={() => handlePartnerClick(product)} className="mt-5 flex w-full items-center justify-center gap-2 rounded-full bg-[#d7b46a] py-3 text-xs font-extrabold text-[#09070d]">Vai al partner <ExternalLink size={14} /></button></div></article>)}</section>
    <section id="partner" className="mt-10 grid gap-6 lg:grid-cols-[1fr_380px]"><div className="rounded-3xl border border-[#d7b46a]/20 bg-[#190e22] p-6 md:p-8"><div className="flex items-center gap-3"><Sparkles className="text-[#d7b46a]" size={19} /><div><p className="section-kicker">Come funziona</p><h2 className="mt-1 text-2xl font-extrabold text-white">Un acquisto, tre livelli di fiducia.</h2></div></div><div className="mt-6 grid gap-4 md:grid-cols-3">{[["01", "Scopri", "Schede editoriali curate, materiali e uso responsabile."], ["02", "Scegli", "Il checkout avviene sul negozio affiliate verificato."], ["03", "Resta", "Reward eventuale solo dopo acquisto confermato e periodo di reso."]].map(([num, title, text]) => <div key={num} className="rounded-2xl border border-white/10 p-4"><p className="text-2xl font-black text-[#d7b46a]">{num}</p><p className="mt-2 text-sm font-extrabold text-white">{title}</p><p className="mt-2 text-xs leading-5 text-[#a99aa7]">{text}</p></div>)}</div></div><aside className="rounded-3xl border border-white/10 bg-[#120b19] p-6"><div className="flex items-center gap-3"><Info size={17} className="text-[#d7b46a]" /><h2 className="font-extrabold text-white">Trasparenza</h2></div><p className="mt-4 text-sm leading-6 text-[#b8a8b4]">Alcuni link potranno essere affiliati. Se acquisti attraverso un link valido, il club potrebbe ricevere una commissione senza costi aggiuntivi per te.</p><div className="mt-5 flex items-start gap-2 border-t border-white/10 pt-4 text-[11px] leading-5 text-[#958493]"><Tag size={14} className="mt-0.5 shrink-0 text-[#d7b46a]" /> Gli ordini, i pagamenti, le spedizioni, i resi e l'assistenza restano a carico del partner.</div></aside></section>
    <p className="mt-8 flex items-start gap-2 text-xs leading-5 text-[#8f7f8d]"><ArrowUpRight size={14} className="mt-0.5 shrink-0 text-[#d7b46a]" /> I prodotti mostrati sono una vetrina di progetto: prima del lancio pubblico sostituiremo i placeholder con partner, SKU, documentazione e link affiliati verificati.</p>
  </main></div>;
}
