/* Velvet Salon: creator studio turns private intent into visible, editable choices with honest local states and no hidden payment promises. */
import { useState } from "react";
import { Link } from "wouter";
import { Check, CheckCircle2, Crown, FileText, ImagePlus, LockKeyhole, Plus, Save, Sparkles, UserRound } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import VelvetNav from "@/components/VelvetNav";
import VelvetRail from "@/components/VelvetRail";
import { useVelvet } from "@/contexts/VelvetContext";

export default function Studio() {
  const { profile, updateProfile } = useVelvet();
  const [displayName, setDisplayName] = useState(profile.displayName);
  const [handle, setHandle] = useState(profile.handle);
  const [bio, setBio] = useState(profile.bio);
  const [category, setCategory] = useState(profile.category);
  const [visibility, setVisibility] = useState(profile.visibility);
  const [mediaTitle, setMediaTitle] = useState("");
  const [mediaFile, setMediaFile] = useState<File | null>(null);
  const [listingTitle, setListingTitle] = useState("");
  const [listingSummary, setListingSummary] = useState("");
  const [tierName, setTierName] = useState("");
  const [price, setPrice] = useState("");
  const [published, setPublished] = useState(false);

  const saveProfile = (event: React.FormEvent) => { event.preventDefault(); updateProfile({ displayName: displayName.trim() || "Valentina", handle: handle.trim().replace(/^@/, "") || "valentina", bio: bio.trim() || "Colleziono riferimenti, processi e conversazioni lente.", category: category.trim() || "Curator", visibility }); toast.success("Profilo aggiornato", { description: "Le tue preferenze sono state salvate nel browser." }); };
  const submitMedia = (event: React.FormEvent) => { event.preventDefault(); if (!mediaFile || !mediaTitle.trim()) return; toast.success("Media inviato in moderazione", { description: `${mediaFile.name} sarà visibile dopo la revisione.` }); setMediaTitle(""); setMediaFile(null); (event.currentTarget as HTMLFormElement).reset(); };
  const saveListing = (event: React.FormEvent) => { event.preventDefault(); if (!listingTitle.trim()) return; toast.success("Bozza salvata", { description: "La bozza resta privata finché non decidi di pubblicarla." }); setPublished(false); };
  const saveTier = (event: React.FormEvent) => { event.preventDefault(); if (!tierName.trim() || Number(price) <= 0) return; toast.success("Livello salvato come bozza", { description: "Nessun addebito viene eseguito in questa versione." }); };

  return <div className="velvet-shell">    <VelvetNav /><main className="container py-12 md:py-16"><div className="flex flex-col justify-between gap-7 border-b border-white/10 pb-8 md:flex-row md:items-end"><VelvetRail label="Creator studio / 01"><h1 className="display-font text-6xl leading-[.95] text-white">Il tuo spazio,<br /><span className="text-[#d7b46a]">le tue regole.</span></h1><p className="mt-5 max-w-xl leading-7 text-[#bcaeba]">Un tavolo semplice per decidere cosa mostrare, a chi e con quale ritmo.</p></VelvetRail><Link href={`/creator/${profile.handle}`} className="flex items-center gap-2 self-start rounded-full border border-white/15 px-4 py-2.5 text-xs font-extrabold text-[#e7d8e1] hover:border-[#d7b46a]/50 hover:text-white">Vedi profilo <Plus size={14} className="rotate-45" /></Link></div>
    <div className="mt-10 grid gap-6 lg:grid-cols-[.95fr_1.05fr]">
      <section className="rounded-3xl border border-white/10 bg-[#120b19] p-6 md:p-8"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-full bg-[#6f5220]/40 text-[#d7b46a]"><UserRound size={18} /></span><div><p className="section-kicker">Identità</p><h2 className="mt-1 text-lg font-extrabold text-white">Profilo pubblico</h2></div></div><form onSubmit={saveProfile} className="mt-7 space-y-4"><div className="grid gap-4 sm:grid-cols-2"><label className="space-y-2 text-xs font-bold text-[#bbaab8]">Nome pubblico<Input value={displayName} onChange={(event) => setDisplayName(event.target.value)} placeholder="Il tuo nome" className="mt-1.5 border-white/10 bg-white/[.04] text-white placeholder:text-[#817582]" /></label><label className="space-y-2 text-xs font-bold text-[#bbaab8]">Handle<Input value={handle} onChange={(event) => setHandle(event.target.value)} placeholder="il_tuo_handle" className="mt-1.5 border-white/10 bg-white/[.04] text-white placeholder:text-[#817582]" /></label></div><label className="block space-y-2 text-xs font-bold text-[#bbaab8]">Bio breve<Textarea value={bio} onChange={(event) => setBio(event.target.value)} placeholder="Cosa succede nel tuo spazio?" className="mt-1.5 min-h-28 border-white/10 bg-white/[.04] text-white placeholder:text-[#817582]" /></label><div className="grid gap-4 sm:grid-cols-2"><label className="space-y-2 text-xs font-bold text-[#bbaab8]">Categoria<Input value={category} onChange={(event) => setCategory(event.target.value)} placeholder="Es. Fotografia" className="mt-1.5 border-white/10 bg-white/[.04] text-white placeholder:text-[#817582]" /></label><label className="space-y-2 text-xs font-bold text-[#bbaab8]">Visibilità<select value={visibility} onChange={(event) => setVisibility(event.target.value as typeof visibility)} className="mt-1.5 h-10 w-full rounded-md border border-white/10 bg-[#2a202d] px-3 text-sm text-white"><option value="listed">Visibile in discovery</option><option value="public">Pubblico con link</option><option value="private">Privato</option></select></label></div><div className="flex flex-wrap items-center justify-between gap-3 pt-2"><span className="flex items-center gap-2 text-xs text-[#968694]"><CheckCircle2 size={14} className="text-[#d7b46a]" /> Le modifiche restano nel tuo browser</span><Button type="submit" className="bg-[#d7b46a] font-extrabold text-[#09070d] hover:bg-[#f1d58f]"><Save size={15} /> Salva profilo</Button></div></form></section>
      <div className="space-y-6"><section className="rounded-3xl border border-[#d7b46a]/20 bg-[#190e22] p-6 md:p-8"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-full bg-[#d7b46a] text-[#09070d]"><ImagePlus size={18} /></span><div><p className="section-kicker">Archivio</p><h2 className="mt-1 text-lg font-extrabold text-white">Carica media</h2></div></div><p className="mt-4 text-sm leading-6 text-[#bbaab8]">Immagini e video vengono indicati come <strong className="text-[#f4d7e1]">in moderazione</strong> prima di una pubblicazione.</p><form onSubmit={submitMedia} className="mt-5 space-y-3"><Input value={mediaTitle} onChange={(event) => setMediaTitle(event.target.value)} placeholder="Titolo del post" className="border-white/10 bg-white/[.04] text-white placeholder:text-[#817582]" /><input type="file" accept="image/*,video/*" onChange={(event) => setMediaFile(event.target.files?.[0] ?? null)} className="block w-full text-xs text-[#bbaab8] file:mr-3 file:rounded-lg file:border-0 file:bg-[#d7b46a] file:px-3 file:py-2 file:text-xs file:font-extrabold file:text-[#09070d]" /><Button type="submit" disabled={!mediaFile || !mediaTitle.trim()} className="bg-[#d7b46a] font-extrabold text-[#09070d] hover:bg-[#f1d58f]"><Plus size={16} /> Invia in moderazione</Button></form></section>
      <section className="rounded-3xl border border-white/10 bg-[#120b19] p-6 md:p-8"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-full bg-white/[.07] text-[#d7b46a]"><FileText size={18} /></span><div><p className="section-kicker">Pubblicazione</p><h2 className="mt-1 text-lg font-extrabold text-white">Nuovo annuncio</h2></div></div><form onSubmit={saveListing} className="mt-5 space-y-3"><Input value={listingTitle} onChange={(event) => setListingTitle(event.target.value)} placeholder="Titolo dell’annuncio" className="border-white/10 bg-white/[.04] text-white placeholder:text-[#817582]" /><Textarea value={listingSummary} onChange={(event) => setListingSummary(event.target.value)} placeholder="Cosa troveranno nello spazio..." className="min-h-24 border-white/10 bg-white/[.04] text-white placeholder:text-[#817582]" /><div className="flex flex-wrap items-center justify-between gap-3"><button type="button" onClick={() => setPublished((value) => !value)} className={`flex items-center gap-2 text-xs font-bold ${published ? "text-[#d7b46a]" : "text-[#968694]"}`}><span className={`grid h-5 w-5 place-items-center rounded border ${published ? "border-[#d7b46a] bg-[#d7b46a] text-[#09070d]" : "border-white/20"}`}>{published && <Check size={13} />}</span>{published ? "Pronto per la pubblicazione" : "Mantieni come bozza"}</button><Button type="submit" variant="outline" className="border-white/15 bg-transparent font-extrabold text-white hover:bg-white/10"><Save size={15} /> Salva bozza</Button></div></form></section>
      <section className="rounded-3xl border border-[#d7b46a]/20 bg-[#190e22] p-6 md:p-8"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-full bg-white/[.07] text-[#d7b46a]"><Crown size={18} /></span><div><p className="section-kicker">Spazio premium</p><h2 className="mt-1 text-lg font-extrabold text-white">Prepara un livello</h2></div></div><p className="mt-4 text-sm leading-6 text-[#bbaab8]">Definisci il nome e il prezzo indicativo. I pagamenti restano disattivati finché non colleghi un provider approvato.</p><form onSubmit={saveTier} className="mt-5 grid gap-3 sm:grid-cols-[1fr_130px]"><Input value={tierName} onChange={(event) => setTierName(event.target.value)} placeholder="Nome livello" className="border-white/10 bg-white/[.04] text-white placeholder:text-[#817582]" /><Input value={price} onChange={(event) => setPrice(event.target.value)} type="number" min="1" placeholder="€/mese" className="border-white/10 bg-white/[.04] text-white placeholder:text-[#817582]" /><Button type="submit" className="bg-white/[.08] font-extrabold text-white hover:bg-white/[.14] sm:col-span-2"><LockKeyhole size={15} /> Salva come bozza</Button></form><p className="mt-4 flex gap-2 text-xs leading-5 text-[#a899a7]"><Sparkles size={14} className="mt-0.5 shrink-0 text-[#d7b46a]" />Trasparenza prima di tutto: niente addebiti in questa versione.</p></section></div>
    </div></main></div>;
}
